.github/workflows/build.yaml
app/routes/__layout/review-changesets.tsx

Supplies the new parameter added in https://github.com/broadinstitute/terra-github-workflows/pull/45

[DDO-2491] Add changeset apply "refresh-only" behavior

---

app/routes/__layout/review-changesets.tsx

It still tries to contact GHA even though there's nothing to sync

[DDO-2507] Fix updating a template version

---

app/components/content/environment/environment-sort.server.ts

[DDO-2512] Remove perf references

---

app/components/content/environment/environment-details.tsx
app/components/content/environment/environment-editable-fields.tsx
app/routes/__layout/environments/$environmentName/edit.tsx
app/routes/__layout/environments/new.tsx
package-lock.json
package.json

[DDO-2521] Expose preventDeletion

---

app/components/content/environment/environment-details.tsx
app/components/content/helpers.tsx
app/routes/__layout/environments/$environmentName/change-versions.tsx

@cahrens made some good feedback, now it has some checkboxes to indicate active state.

[DDO-2532] Improve visibility into what charts are selected for monolith

---

app/components/content/app-version/app-version-editable-fields.tsx
app/components/content/chart-version/chart-version-editable-fields.tsx
app/components/content/environment/environment-editable-fields.tsx

Using soft wrapping had some downstream impacts :/ This is better, more standard, just didn't fully think through how hard breaking would interact with soft wrapping.

[DDO-2534] Use normal line breaking everywhere

---

app/components/logic/pretty-print-description.tsx

I didn't want to install a full markdown parser so I just did a URL to handle basic URLs. I forgot that ampersands are valid.

[DDO-2554] Fix URL parsing in descriptions

---

app/components/content/changeset/changeset-entry.tsx
app/components/interactivity/inactive-nav-button.tsx
app/components/interactivity/list-pagination-controls.tsx
app/routes/__layout/charts/$chartName/chart-releases/$chartReleaseName/applied-changesets.tsx
app/routes/__layout/clusters/$clusterName/($namespace).chart-releases/$namespace.$chartName/applied-changesets.tsx
app/routes/__layout/environments/$environmentName/chart-releases/$chartName/applied-changesets.tsx
app/routes/__layout/review-changesets.tsx

Changesets now minimized by default when there's many of them and the list handles pagination in a good-enough way.

[DDO-2564] Minimized changesets and paginated lists

---

app/routes/__layout/review-changesets.tsx

Copy-paste error that I didn't catch until now.

[DDO-2578] Fix refresh-only from Beehive

---

app/root.tsx
styles/safe-area.css

[DDO-2587] I suddenly hate apple

---

.github/workflows/build.yaml

I'll merge with #major to do the major version bump.

Release 1.0 and switch to patch version bumping

---

app/components/interactivity/inactive-nav-button.tsx
app/components/interactivity/list-controls.tsx
app/components/interactivity/list-pagination-controls.tsx
app/components/interactivity/nav-button.tsx

[DDO-2591] Fix button issue

---

app/routes/__layout/charts/$chartName/chart-releases/$chartReleaseName.tsx
app/routes/__layout/clusters/$clusterName/($filterNamespace).chart-releases/$namespace.$chartName.tsx
app/routes/__layout/environments/$environmentName.tsx
app/routes/__layout/environments/$environmentName/chart-releases/$chartName.tsx

https://broadinstitute.slack.com/archives/C03TNMDJ0F8/p1674509344504479?thread_ts=1674251708.095659&cid=C03TNMDJ0F8

[DDO-2593] Hide PD config buttons while they don't work

---

app/routes/_layout.misc.tsx

Remix supports streaming responses out of the box now. This is actually way more resilient than my earlier hack to load the page ignoring errors.

[DDO-2621] Use `defer` on the Misc page

---

app/routes/_layout.environments.$environmentName.change-versions.tsx

I was already doing e.preventDefault() so this actually doesn't matter but I saw a tweet and realized I did this wrong

[DDO-2624] Set the type on a button

---

app/features/sherlock/app-versions/set/app-version-picker.tsx

There's no movement on application versions getting reported for legacy apps and folks are confused why Beehive doesn't know about their commits.

[DDO-2646] When an app doesn't report git info, hide those buttons

---

app/components/layout/inset-panel.tsx
app/components/layout/outset-panel.tsx
app/routes/_layout._index.tsx
app/routes/_layout.environments.new.tsx
app/routes/_layout.tsx

- [`/environments/new?lifecycle=static`](https://github.com/broadinstitute/beehive/commit/bbb194585fbc80977b57dd3232a7270e4c17f243)
- [allow vertical scrollbar on homepage](https://github.com/broadinstitute/beehive/commit/1a200dd7646efde39b935f0ac312c4cda7cd452e)
- [add horizontal scroll-snapping](https://github.com/broadinstitute/beehive/commit/859607779a09d06456e9f6cd993a6a51f6dc3952)
- [remove deprecated double-width panels](https://github.com/broadinstitute/beehive/commit/34a878d8a58d0afde915b505e9f054b9578aec09)

[DDO-2648] Misc styling changes

---

app/components/interactivity/action-button.tsx
app/components/panel-structures/action-box.tsx
app/components/panel-structures/big-action-box.tsx
app/components/panel-structures/item-details.tsx
app/features/color-class-names.ts
app/features/sherlock/app-versions/app-version-colors.tsx
app/features/sherlock/chart-versions/chart-version-colors.tsx
app/features/sherlock/charts/chart-colors.tsx
app/features/sherlock/clusters/cluster-colors.tsx
app/features/sherlock/environments/delete/environment-delete-description.tsx
app/features/sherlock/environments/environment-colors.tsx
app/features/sherlock/environments/view/environment-offline-icon.tsx
app/features/sherlock/pagerduty-integrations/pagerduty-integration-colors.tsx
app/root.tsx
app/routes/_layout._index.tsx
app/routes/_layout.charts.$chartName.chart-releases.$chartReleaseName.tsx
app/routes/_layout.clusters.$clusterName.($filterNamespace).chart-releases.$namespace.$chartName.tsx
app/routes/_layout.environments.$environmentName.chart-releases.$chartName.tsx
app/routes/_layout.environments.$environmentName.delete.tsx
app/routes/_layout.environments.$environmentName.tsx
app/routes/api.sherlock.set-environment-offline.ts
package-lock.json
package.json

https://broadinstitute.slack.com/archives/C03TNMDJ0F8/p1675978135264359

[DDO-2640] Offline support

---

app/routes/_layout._index.tsx

Not in love with "**New!** New ..." but it's succinct and whatever

[DDO-2669] Change announcement text

---

app/features/sherlock/environments/offline/environment-schedule-fields.tsx

[DDO-2669] More aggressive default schedule

---

app/features/sherlock/chart-releases/list/chart-release-sorter.ts
app/features/sherlock/charts/list/chart-sorter.ts

Noticed this wasn't working quite as expected

[DDO-2715] Fix chart release sort order

---

app/routes/_layout._index.tsx

[DDO-2720] 

---

app/features/sherlock/chart-releases/view/chart-release-details.tsx
app/features/sherlock/environments/view/environment-details.tsx
app/routes/_layout._index.tsx
app/routes/api.argocd.badge.ts

The example links to msft-dev because that's a well-known stable BEE and the resulting page makes it obvious how to look at other BEEs.

[DDO-2731] Add Kibana link

---

app/features/sherlock/chart-releases/view/chart-release-details.tsx

For chart releases, look over longer

[DDO-2731] Improved Kibana link

---

app/components/interactivity/copyable-text.tsx
app/features/sherlock/mutate-controls.tsx
app/features/sherlock/pagerduty-integrations/pagerduty-integration-colors.tsx
app/features/sherlock/users/edit/user-editable-fields.tsx
app/features/sherlock/users/list/list-user-button-text.tsx
app/features/sherlock/users/list/matchUser.ts
app/features/sherlock/users/list/user-sorter.ts
app/features/sherlock/users/user-colors.tsx
app/features/sherlock/users/view/user-details.tsx
app/features/sherlock/users/view/user-general-details.tsx
app/routes/_layout._index.tsx
app/routes/_layout.users.$userEmail._index.tsx
app/routes/_layout.users.$userEmail.edit.tsx
app/routes/_layout.users.$userEmail.tsx
app/routes/_layout.users.tsx
app/routes/r.README.md
app/routes/r.user.$.ts
app/themes/dark.tailwind.css
app/themes/fallback.tailwind.css
app/themes/light.tailwind.css
package-lock.json
package.json
tailwind.config.js

Mostly just laying foundation for stuff later on. Lets people change their display name.

[DDO-2709] Expose Users API in the UI

---

app/features/sherlock/environments/list/environment-sorter.ts
app/features/sherlock/environments/list/list-environment-button-text.tsx
app/features/sherlock/environments/new/environment-creatable-fields.tsx
app/features/sherlock/environments/set/sidebar-select-environment.tsx

Okay yeah I'm gonna need to come up with some better sorting system

[DDO-2723] Show swatomation as a good default

---

app/features/sherlock/users/list/matchUser.ts

[DDO-2709] Make user search case insensitive

---

app/features/github/run-gha.ts
app/routes/_layout.charts.$chartName.chart-releases.$chartReleaseName.delete.tsx
app/routes/_layout.clusters.$clusterName.($filterNamespace).chart-releases.$namespace.$chartName.delete.tsx
app/routes/_layout.clusters.$clusterName.($filterNamespace).chart-releases.add.$chartName.tsx
app/routes/_layout.environments.$environmentName.chart-releases.$chartName.delete.tsx
app/routes/_layout.environments.$environmentName.chart-releases.add.$chartName.tsx
app/routes/_layout.environments.$environmentName.delete.tsx
app/routes/_layout.environments.new.tsx
app/routes/_layout.review-changesets.tsx
app/routes/api.sherlock.set-environment-offline.ts

Abstracts the existing GHA-calling code and adds usage of the new bee-sync for adding or deleting a chart release

[DDO-2740] Improved GHA support

---

app/features/sherlock/chart-releases/set/sidebar-select-multiple-chart-releases.tsx
app/features/sherlock/environments/view/environment-details.tsx
app/features/sherlock/mutate-controls.tsx
app/helpers/date.ts
app/routes/_layout.environments.$environmentName.adjust-bulk-update-defaults.tsx
app/routes/_layout.environments.$environmentName.change-versions.tsx
app/routes/_layout.environments.$environmentName.tsx
package-lock.json
package.json

The screen looks like this:
and when it's set, the monolith page has a bolded extra bit of explanation:
Thoughts on copy? Something I can do to make the interface clearer?

[DDO-2741] Allow exclusion from monolith in Beehive

---

app/components/logic/theme.tsx
app/themes/extra-dark.tailwind.css
app/themes/extra-light.tailwind.css

don't worry, i'm not going to change the interface for anyone by default, it's just additional options in the dropdown because i kinda don't love my first pass at dark mode. leave me alone ok :(

some tweaks to the beehive system theming

---

app/routes/_layout.environments.$environmentName.adjust-bulk-update-defaults.tsx

[DDO-2741] Jenkins clarification

---

app/components/interactivity/inline-popover.tsx
app/features/sherlock/chart-releases/chart-release-link-chip.tsx
app/features/sherlock/chart-releases/view/app-instance-popover-contents.tsx
app/features/sherlock/chart-releases/view/chart-release-details.tsx
app/features/sherlock/charts/view/app-popover-contents.tsx
app/features/sherlock/charts/view/chart-details.tsx
app/routes/_layout.apps.$chartName.from-dev.tsx
app/routes/_layout.apps.$chartName.from-staging.tsx
app/routes/_layout.apps.$chartName.tsx

- Fix inline popover chevron position on safari
- Fix argocd link chip sizing on firefox
- Improve app instance popover contents
- Improve app popover contents
- Change Changeset kickoff buttons to say "Review and Ship" over "Click to Review"

[DDO-2753] app view improvements

---

app/components/layout/inset-panel.tsx
app/features/sherlock/chart-releases/view/app-instance-entry.tsx
app/helpers/panel-size.ts
app/helpers/transition-view.ts
app/routes/_layout.apps.$chartName._index.tsx
app/routes/_layout.apps.$chartName.from-dev.tsx
app/routes/_layout.apps.$chartName.from-staging.tsx
app/routes/_layout.apps.$chartName.tsx
tailwind.config.js

The "Chelsea doesn't have an external monitor right now" update :D

[DDO-2753] Better laptop/mobile support and error handling

---

app/features/sherlock/environments/edit/environment-editable-fields.tsx
app/features/sherlock/users/list/user-sorter.ts
app/features/sherlock/users/set/sidebar-select-user.tsx
app/routes/_layout.environments.$environmentName.edit.tsx
app/routes/_layout.environments.new.tsx

Technically independent of https://github.com/broadinstitute/sherlock/pull/145 because the API didn't change.

[DDO-2759] Show user list for environment owner field

---

app/features/sherlock/changesets/list/changeset-entry.tsx
app/features/sherlock/changesets/recreate/changeset-recreate-button.tsx
app/features/sherlock/environments/offline/environment-offline-icon.tsx
app/routes/_layout.review-changesets.tsx
app/routes/api.sherlock.recreate-changeset.ts
app/routes/api.sherlock.set-environment-offline.ts
package-lock.json
package.json
remix.config.js

Also bumps Sherlock's client library and Remix's versions to include my Remix bugfix so I don't forget later. Fixes a few linting complaints due to new tooling versions.
Tested locally against a local copy of Sherlock's prod DB. I'm really closely copying how the stop/start button works.
Super low, this is purely additive.

[DDO-2929] Expose revert/recreate functionality

---

app/features/sherlock/chart-versions/set/chart-version-picker.tsx

https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1687980558706099?thread_ts=1687967828.260319&cid=CQ6SL4N5T

[DDO-2932] chart version field validation

---

app/routes/_layout.misc.tsx

I want to change this endpoint in Sherlock and it's honestly easier for me to just not call it from Beehive than to try to do the changes in a backwards compatible way. Beehive only calls it for debugging purposes.
This change just means that the misc page in Beehive won't tell you whether you are suitable or not. It doesn't impact Sherlock actually doing permissions based on it, that'll still happen.
Ran it locally.
None

[DDO-2942] Remove Beehive's usage of Sherlock's /my-user

---

app/features/sherlock/chart-releases/add/chart-release-creatable-cluster-fields.tsx
app/features/sherlock/chart-releases/add/chart-release-creatable-environment-fields.tsx

Visited the BEE template modification UI and noticed a typo. :/

[DDO-2955] Fix typo

---

.github/workflows/dependency-review.yaml
.github/workflows/dependency-review.yml

Like https://github.com/broadinstitute/sherlock/pull/214 but for Beehive

[DDO-2982] Add GitHub Dependency Review

---

app/features/sherlock/environments/environment-help-copy.tsx

It's a good doc, might as well link it, might make it more prominent in the future.

[DDO-3070] Link to IA's "How to BEE" doc

---

app/routes/_layout.charts.$chartName.chart-releases.$chartReleaseName.deploy-hooks.tsx
app/routes/_layout.clusters.$clusterName.($filterNamespace).chart-releases.$namespace.$chartName.deploy-hooks.tsx
app/routes/_layout.environments.$environmentName.chart-releases.$chartName.deploy-hooks.tsx
app/routes/_layout.environments.$environmentName.deploy-hooks.tsx

I missed one, going too fast to try to make demo o'clock

[DDO-3089] Fix IAP on deploy hook pages

---

app/routes/_layout._index.tsx

[DDO-3089] Update Beehive's header to promote deploy hooks

---

app/features/sherlock/chart-releases/view/chart-release-details.tsx
app/features/sherlock/mutate-controls.tsx
app/routes/_layout._index.tsx

[DDO-3089] Add deploy hook buttons to one more place in Sherlock

---

app/features/sherlock/changesets/list/changeset-entry.tsx
app/features/sherlock/users/view/user-link.tsx
package-lock.json
package.json

That latter one actually hides normally if you're the one viewing, because I figured it was superfluous. I manually tricked it in order to take a screenshot.
See above
Miniscule

[DDO-3113] Expose Changeset Identity

---

app/components/interactivity/action-button.tsx
app/components/logic/pretty-print-time.tsx
app/components/panel-structures/action-box.tsx
app/components/panel-structures/big-action-box.tsx
app/helpers/google.server.ts
app/routes/_layout.review-changesets.tsx
package-lock.json
package.json
setup-env.bash

All of this is gated behind `RELEASE_PROTECTION_CALENDAR_ID` being present, so this is safe to ship now. If that's not present, behavior is identical to before. It's also identical to before for lower environments.

[DDO-3148] Show release protection calendar events in Beehive

---

app/components/interactivity/action-button.tsx
app/components/panel-structures/sidebar-filter-list.tsx
app/features/sherlock/chart-releases/set/sidebar-select-multiple-chart-releases.tsx
app/features/sherlock/environments/change-versions/change-environment-versions-sidebar-modes.ts
app/features/sherlock/environments/environment-help-copy.tsx
app/routes/_layout.environments.$environmentName.change-versions.tsx

1. Improve the help copy for environments to better highlight the important info
2. All select none/default/all buttons to the bulk release screen
Local, also with local against prod
None

[DDO-3156] Select None/Default/All; Improved Environment Copy

---

app/routes/_layout.review-changesets.tsx

alphabetical order by chart release name. change caused a reformat of the code but the entire change is just adding a
```
.sort((a, b) =>
a.chartReleaseInfo?.name && b.chartReleaseInfo?.name
? a.chartReleaseInfo.name.localeCompare(b.chartReleaseInfo.name)
: 0,
)
```
to the end of the changeset request. In the future I think Sherlock's endpoint might do this automatically, but this is the fastest solution right now.
Tested locally
Extremely low

[DDO-3174] Sort changesets on review page

---

app/components/logic/theme.tsx
app/routes/_layout._index.tsx
app/themes/halloween-dark.tailwind.css
app/themes/halloween-light.tailwind.css

[DDO-3223] HALLOWEEN

---

package-lock.json
package.json

No need to use prerelease versions anymore. Updated everything including the node requirement
"I ran it"
Low

[DDO-3205] Remix v2's mainline 2.1.0

---

app/features/sherlock/pagerduty-integrations/trigger-incident/incident-trigger-success-panel.tsx

From https://broadinstitute.slack.com/archives/CA1481PRN/p1697731842779169?thread_ts=1697730636.199099&cid=CA1481PRN

[DDO-3248] Tweak incident created text

---

app/routes/_layout.charts.$chartName.contract-testing.tsx

Provides more information for errors that happen on the beehive end.

DDO-3265 Dump error message for pact

---

app/components/logic/notification.tsx
app/components/panel-structures/action-box.tsx
app/features/sherlock/deploy-hooks/edit/github-actions-deploy-hook-edit-panel.tsx
app/features/sherlock/deploy-hooks/edit/slack-deploy-hook-edit-panel.tsx
app/features/sherlock/deploy-hooks/test/deploy-hook-test-panel.tsx
app/features/sherlock/deploy-hooks/test/test-github-actions-deploy-hook-action.server.ts
app/features/sherlock/deploy-hooks/test/test-slack-deploy-hook-action.server.ts
app/features/sherlock/users/view/user-details.tsx
app/routes/_layout._index.tsx
app/routes/_layout.charts.$chartName.chart-releases.$chartReleaseName.deploy-hooks.github-actions.$id.test.tsx
app/routes/_layout.charts.$chartName.chart-releases.$chartReleaseName.deploy-hooks.slack.$id.test.tsx
app/routes/_layout.clusters.$clusterName.($filterNamespace).chart-releases.$namespace.$chartName.deploy-hooks.github-actions.$id.test.tsx
app/routes/_layout.clusters.$clusterName.($filterNamespace).chart-releases.$namespace.$chartName.deploy-hooks.slack.$id.test.tsx
app/routes/_layout.environments.$environmentName.chart-releases.$chartName.deploy-hooks.github-actions.$id.test.tsx
app/routes/_layout.environments.$environmentName.chart-releases.$chartName.deploy-hooks.slack.$id.test.tsx
package-lock.json
package.json

Was able to run all four combinations from local Beehive (GHA dry run, real, Slack dry run, real)
Very low

[DDO-3289] Add deploy hook test capability

---

app/routes/_layout.charts.$chartName.chart-releases.$chartReleaseName.change-versions.tsx
app/routes/_layout.clusters.$clusterName.($filterNamespace).chart-releases.$namespace.$chartName.change-versions.tsx
app/routes/_layout.environments.$environmentName.chart-releases.$chartName.change-versions.tsx

Cost of HTML forms, I guess. If we have this happen in other cases we might want to take a different approach to either forms or how this stuff is tested / typed but I don't want to over-react on one instance
Tested locally, dodges the issue
Very low

[DDO-3314] Fix toHelmfileRefEnabled handling

---

app/features/sherlock/deploy-hooks/edit/github-actions-deploy-hook-editable-fields.tsx

[DDO-3484] Improve GHA deploy hook docs

---

app/features/sherlock/ci/view/ci-run-resource-status-button.tsx

A request from Trevyn, "so that we don’t have to dig into the pop up to see if anything failed."
Rather than always using `ciRuns[0]` as the one to show on the button, it first checks if there's a non-success in the list that doesn't have a matching more recent success and shows the most recent one of those if possible.
This is O^2 and I don't care, we're talking about a 10 element array here in 99.99% of cases, we'd wait longer on memory allocation for an accumulator or something than just doing it this way.
Testing done manually, screenshot above. Risk very low.

[DDO-3615] Prioritize non-successes on CiRun widget

---

.github/workflows/build.yaml

Like https://github.com/broadinstitute/thelma/pull/279 and https://github.com/broadinstitute/sherlock/pull/535 but for Beehive

[DDO-3622] Publish images to super-prod GAR

---

CONTRIBUTING.md

Cutting over URLs, access SAs, and audiences in line with the new Sherlock and Beehive. This is a baby version of the Thelma PR that does most of the brunt work here.
See also:
- https://github.com/broadinstitute/thelma/pull/295
- https://github.com/broadinstitute/sherlock/pull/537
- https://github.com/broadinstitute/beehive/pull/467
- https://github.com/broadinstitute/terra-helmfile/pull/5471
- https://github.com/broadinstitute/terra-github-workflows/pull/189

[DDO-3622] Cut over URLs

---

app/features/sherlock/environments/new/environment-creatable-fields.tsx
app/features/sherlock/environments/offline/environment-schedule-fields.tsx
app/routes/_layout.environments.new.tsx

As suggested in, https://broadinstitute.slack.com/archives/C0DSD41QT/p1714578650478169?thread_ts=1714576725.205259&cid=C0DSD41QT, this is a nudge towards saving money and will save that money-saving path a few clicks.
**Before:
After:

[DDO-3653] Default new BEEs to no boot-up schedule

---

.github/dependabot.yml
.github/workflows/check-ticket.yaml

Adds a GitHub Action to check that tickets are in PR titles; configures dependabot to include one.

[DDO-3641] [DDO-3640] Enforce ticket 

---

app/routes/_layout.roles.$roleName.assignments.$userEmail.delete.tsx
app/routes/_layout.roles.$roleName.assignments.$userEmail.edit.tsx
app/routes/_layout.roles.$roleName.assignments.$userEmail.tsx
app/routes/_layout.roles.$roleName.assignments.new.tsx
app/routes/_layout.roles.$roleName.assignments.tsx
app/routes/_layout.roles.$roleName.delete.tsx
app/routes/_layout.roles.$roleName.edit.tsx
app/routes/_layout.roles.$roleName.tsx
app/routes/_layout.roles.tsx

Now that we've got Beehive and Sherlock fully wired up talking about Roles and RoleAssignments in prod (i.e. we actually have super-users who can get non-empty responses back) there's a few small tweaks I'm making:
- Fixed handleIAP not being called on some loaders/actions, causes 401s/407s
- Making page titles a bit longer since a lot of how they're used is in history rather than just tabs
- Fixed "is super user" detection to make fewer requests (improves page load times and dodges an async handling issue that was present)
- Fixes imports in a few places my IDE fussed over
I primarily tested this by running this local Beehive against Sherlock's prod instance and played with Katie's role assignment a bit since she's out
Low

[DDO-3761] Role fixes

---

app/features/sherlock/role-assignments/edit/role-assignment-editable-fields.tsx
app/features/sherlock/role-assignments/new/role-assignment-creatable-fields.tsx
app/features/sherlock/role-assignments/view/role-assignment-details.tsx
app/features/sherlock/roles/edit/role-editable-fields.tsx
app/features/sherlock/roles/view/role-details.tsx
app/routes/_layout.roles.tsx

UX tweaks to convey the behavioral changes proposed in https://github.com/broadinstitute/sherlock/pull/595
Local against dev; all logic tested on Sherlock's end
Low

[DDO-3772] Handle computing suspension based on suitability
