- app/components/content/environment/environment-creatable-fields.tsx
It should basically always be "bee". I'd meant to fully remove the field but decided against it because it could cause other bugs on the page and no one has ever actually used that page before
> [DDO-2503] Provide a default for the values base for templates

- app/components/content/app-version/app-version-details.tsx
- app/components/content/app-version/app-version-editable-fields.tsx
- app/components/content/chart-release/chart-release-details.tsx
- app/components/content/chart-version/chart-version-details.tsx
- app/components/content/chart-version/chart-version-editable-fields.tsx
- app/components/content/chart/chart-creatable-fields.tsx
- app/components/content/chart/chart-details.tsx
- app/components/content/chart/chart-editable-fields.tsx
- app/components/content/cluster/cluster-creatable-fields.tsx
- app/components/content/cluster/cluster-details.tsx
- app/components/content/cluster/cluster-editable-fields.tsx
- app/components/content/environment/environment-creatable-fields.tsx
- app/components/content/environment/environment-details.tsx
- app/components/content/environment/environment-editable-fields.tsx
- app/components/interactivity/enum-select.tsx
- app/components/logic/pretty-print-description.tsx
- app/components/logic/pretty-print-time.tsx
- app/routes/__layout/environments.tsx
- app/routes/__layout/review-changesets.tsx
- package-lock.json
- package.json
- Allow simple markdown links in all descriptions
- Note this for app/chart version descriptions
- Fix some type issues arising from Remix being a step more precise in how it types loaders and actions
- Make the date printing work for both strings and actual date objects
- Add the description field to environment's edit field set
- Make the description appear on environments when it is set
- Make the environment list links automatically open the chart list to guide people towards that view 
- It's a heavier-weight request but it should load in parallel because of Remix
Requires https://github.com/broadinstitute/sherlock/pull/110 to be deployed
> [DDO-2534] Expose environment description

- app/components/content/app-version/app-version-editable-fields.tsx
- app/components/content/chart-version/chart-version-editable-fields.tsx
- app/components/content/environment/environment-editable-fields.tsx
I didn't know that soft wrapping existed and thought the options were just "hard" and "off". Soft is definitely what we want because it doesn't send the wrap newline characters to Sherlock
> [DDO-2534] Use `soft` wrapping instead of `hard` everywhere

- app/components/boundaries/error-boundary.tsx
- app/components/content/chart/chart-details.tsx
- app/components/content/environment/environment-details.tsx
Charts that have apps and static environments now get links to their respective accelerate metrics pages in Grafana.
Also fixes an incorrect text color inside the error boundary that I noticed while debugging #63
> [DDO-2568] Link to Grafana from Beehive

- app/components/content/chart-release/chart-release-details.tsx
- app/components/content/chart-release/chart-release-link-chip.tsx
- app/csp.server.ts
- app/routes/__layout/index.tsx
Can't style them at all but who cares, it's neat. I made them link back to the chart release in ArgoCD. Had to tweak the CSP but that's what it's there for, was nice to see it do its job.
> [DDO-2575] Add ArgoCD statuses

- app/components/content/changeset/changeset-entry.tsx
- app/components/content/chart-release/chart-release-sort.server.ts
- app/routes/__layout/charts/$chartName/chart-releases/$chartReleaseName/change-versions.tsx
- app/routes/__layout/clusters/$clusterName/($filterNamespace).chart-releases/$namespace.$chartName/change-versions.tsx
- app/routes/__layout/environments/$environmentName/chart-releases/$chartName/change-versions.tsx
It now sorts and shows the version. Could refactor to make this code cleaner but that's a longer task and frankly find/replace make this kind of edit just not that cumbersome.
> [DDO-2595] Improvements to /change-versions chart release picker

- app/entry.server.tsx
[renderToPipeableStream](https://beta.reactjs.org/reference/react-dom/server/renderToPipeableStream) is what Remix uses to server-side render React and then send it to the browser upon initial page load.
The way it handles `<Suspense>` is to inject inline script tags to wire up the websocket. That works great, except for us, because the Content Security Policy shoots down those `unsafe-inline` scripts. Turns out that renderToPipeableStream accepts a nonce though, which is pretty sweet.
I was actually already mucking around in the renderToPipeableStream call because that's how I set the CSP header in the first place. I think I can just move the Remix context read outside of the onShellReady callback and it should still work... and then I have the nonce to inject into …
> [DDO-2621] Pass CSP nonce to renderToPipeableStream

- app/features/sherlock/app-versions/set/app-version-picker.tsx
- app/features/sherlock/chart-releases/change-versions/change-chart-release-versions-panel.tsx
- app/features/sherlock/chart-versions/set/chart-version-picker.tsx
This being omitted makes manual chart version selection write the wrong field names into the request body. Added the flag and fixed the type system to prevent this in the future. I messed up during the refactoring and didn't adjust the type system properly so this issue got through :/
> [DDO-2628] Fix chart version picker flags

- app/routes/r._index.ts
[https://beehive.dsp-devops.broadinstitute.org/r](https://beehive.dsp-devops.broadinstitute.org/r) <- you'll see what I'm talking about, it needs to go to https://beehive.dsp-devops.broadinstitute.org/r/README
> [DDO-2625] Fix `/r` -> README.md redirect

- app/features/sherlock/environments/new/duplicate-bee-warning.tsx
- app/routes/_layout.environments.new.tsx
It only shows when the user is making a BEE, and only after they've selected a template. It matches existing BEEs they own with the same template. I'm reusing the "link chips" for the environment that are around the rest of the UI so it's interactive.
> [DDO-2637] Tell users about duplicate BEEs they have

- app/features/sherlock/environments/view/environment-offline-icon.tsx
So this little popup is the first time in Beehive that I'm using `useFetcher`, which allows non-navigation communication with the Remix backend (ever notice that form submissions everywhere else always cause a redirect?)
It works great, only thing I missed was that I accidentally inferred loading state from the navigation context instead of from the special fetcher that's doing this request. This just means that the little Beehive loading icon doesn't appear as you'd expect. It's only really apparent in prod/dev because of all the additional latency from the proxies--locally the button appears to work pretty much instantly.
> [DDO-2640] Make the popover loading icon react properly to the non-navigation fetch

- app/features/sherlock/environments/new/environment-creatable-fields.tsx
I'm going to add this to Sherlock but Beehive is faster for both me and the end-user (their browser will client-side validate)
> Disallow capital letters in environment names

- app/components/layout/header.tsx
I was doing this weird thing of showing the _previous_ page on mobile, because that made sense when mobile horizontal scrolling was wonky, but now that I got scroll snapping working it's fine and I think simpler is better.
In the future I'm going to want the search bar to be here (showing the title of the page in the top bar there is kinda useless) but what it means right now is I just want to make it simpler and leave it.
The behavior now is to show the last breadcrumb, rather than the second to last with a reversed arrow.
> [DDO-2663] Simplify top bar behavior on mobile

- app/components/interactivity/time-field.tsx
- app/features/sherlock/sherlock.server.ts
- app/helpers/date.ts
- app/routes/_layout.environments.$environmentName.schedule.tsx
- app/routes/_layout.environments.$environmentName.tsx
- app/routes/_layout.environments.new.tsx
- For existing environments, default to showing schedule as disabled
- Enable the link from the environment details page to edit the schedule
- Enable the fields during environment creation (**this enables a 7am to 7pm schedule by default for new bees created through beehive**)
- Fix the backend so it uses the iso timestamp it was sent from the frontend
> [DDO-2669] Fully enable scheduling in Beehive #minor

- app/components/logic/notification.tsx
- app/routes/_layout.tsx
Turns out that the notifications are mostly just good feedback that The Thing Happened, so it makes sense to actually allow duplicates instead of removing them with some sort of ID like I was doing.
> [DDO-2705] Allow duplicate notifications

- app/features/sherlock/chart-releases/view/app-instance-popover-contents.tsx
`https://beehive.dsp-devops.broadinstitute.org/environments/dev/charts/firecloudorch/change-versions` should be `https://beehive.dsp-devops.broadinstitute.org/environments/dev/chart-releases/firecloudorch/change-versions`
> Fix popover link

- app/routes/_layout.environments.$environmentName.change-versions.tsx
- app/routes/_layout.review-changesets.tsx
Greg Rushton found two (pretty embarrassing) issues with Beehive stemming from me not getting how my React state and HTML form checkboxes interact (meaning I wasn't sending the right info to Sherlock's API when checkboxes were unchecked).
"When I deselect charts in the bulk environment update screen, they still seem to be included when I have Sherlock calculate out the changes."
So in Sherlock's API, it used to be that if you passed "includeCharts" in a changeset request, it worked like terraform `--target` (suddenly everything was excluded by default). Beehive would just always set this field, once per each chart to include. That worked great until I built out the "exclude my chart from monolith by default" capability. Suddenly, Beehive wasn't being quite specific enough -- it was …
> [DDO-2797] Fix "select X to include" checkboxes

- app/features/sherlock/changesets/list/changeset-entry.tsx
- app/routes/_layout.review-changesets.tsx
Split from #188, some styling fixes for the review changeset page.
Before:
After:
It also makes the cursor have the "this is a button" pointer look but I can't screenshot that very well
> [DDO-2798] Fix Changeset checkbox sizing

- remix.config.js
Docs here https://remix.run/docs/en/main/pages/v2#formmethod
Remix accidentally lowercases the HTTP method in some of its APIs, and they're fixing that in v2. Lucky for us, we literally never use `formMethod` in Beehive, so we can enable this flag to surpress the warning for free.
Checked via the usual "run it" and also double-check that no usages snuck in somewhere:
> [DDO-2800] Add v2_normalizeFormMethod

- app/features/sherlock/chart-versions/view/chart-version-details.tsx
I definitely did a find-replace of "app" -> "chart" when I ported this from app-version-details.tsx, whatever. No testing and zero risk IMO, check the diff.
> [DDO-2832] Fix typo

- app/components/interactivity/external-nav-button.tsx
- app/features/sherlock/environments/view/environment-details.tsx
You can tell I've been seeing clips from Typescript influencers on Twitter because I used `Pick<ComponentProps<"a">, "target">` to copy the builtin target prop's autocomplete.
(Got a request for the button to open in a new tab so 🪄. Adds the little arrow too that I use elsewhere for the new tab links)
Ran it. The link opens in a new tab. 🤷
Realistically zero IMO.
> [DDO-2833] Make Terra UI link open in a new tab

- app/routes/_layout.charts.$chartName.chart-releases.$chartReleaseName.delete.tsx
Copy paste error on my part -- see that the file name has `$chartName` in it but not `$environmentName`, so the existing redirect's usage of `params.environmentName` was resolving to an empty string (and Sherlock was 404-ing on an empty string). The right thing to do is redirect to the list of chart releases for the chart, not for an environment that might not exist for cluster-only releases.
> app/routes/_layout.charts.$chartName.chart-releases.$chartReleaseName.delete.tsx
```diff
- `/environments/${params.environmentName}/chart-releases`
+ `/charts/${params.chartName}/chart-releases`
```
Works locally.
This didn't affect the deletion, just which page you were sent to upon completion from this specific page.
> [DDO-2878] Fix deletion redirect

- app/features/sherlock/changesets/list/changeset-entry.tsx
Kinda forgot that Beehive ostensibly supports mobile devices for a moment.
Super tiny change, just goes from 
to
> [DDO-2929] Fix revert/recreate on mobile

- app/features/sherlock/environments/new/environment-creatable-fields.tsx
Maybe I should make Sherlock more opinionated here but regardless this Regex is considered invalid by Chrome even though Regexr seemed fine with it. Whatever.
Go to https://beehive.dsp-devops.broadinstitute.org/environments/new, open your browser console, and then type in the name field. You'll see an invalid regex error. Edit the pattern from the browser console to backslash the `-` in the character class to include the hyphen and the error will be resolved (the field will correctly flag capitalized inputs as invalid).
None
> [DDO-2940] Fix environment name regex

- app/routes/_layout._index.tsx
- app/routes/r.README.md
- app/routes/r.app.$.ts
1. Hide the "new" banner text (keep it commented for when something launches)
2. Hide Clusters and Charts buttons
3. Make Environments button reference BEEs
4. Make Apps button reference Deployment
5. Add a link to the redirects feature to the homepage
6. Make `/r/apps/<chart-name>` work as expected
> [DDO-2950] Tweak Beehive homepage

- app/features/sherlock/chart-releases/view/app-instance-popover-contents.tsx
Everywhere else in the UI correctly references `/applied-changesets`, because this is a popover it works differently (has to use absolute path) so this slipped through
> [DDO-2952] Fix version history link

- app/routes/_layout.review-changesets.tsx
Take advantage of https://github.com/broadinstitute/terra-github-workflows/pull/93. We already have a stupid/simple mechanism for telling the Remix action which chart release names aren't templates and should be actually synced... so I just copied that to pass back a list of changeset IDs that aren't templates. The alternative would be a bunch of backend queries or passing some different value in a list and correlating it, so this is just easier.
I knew the action itself worked per https://github.com/broadinstitute/terra-github-workflows/pull/93, and I knew that the request was properly-formed per Beehive's logging (it dumps the request body)... 
So I ran this branch's Beehive against Sherlock's production instance (safer than deploying this branch into Beehive prod outright). It worked! …
> [DDO-2994] Pass changeset IDs to sync-relase.yaml

- app/routes/r.user.$.ts
Problem of having deprecated APIs in your client library is that they still typecheck :/ messed this one up; should just call the other method. Does the same thing, this one just works a little better (it handles `me` and `self` and stuff better)
Ran locally, not much to test, it works.
None
> [DDO-2989] One more instance of Beehive hitting the v2 user API

- foundation.yaml
I'm experimenting with [backstage](https://backstage.spotify.com/) for Foundation purposes and need some real services to be able to try features out on my dev instance so I'm using sherlock and beehive. This metadata file is what enables services to be registered in the foundation service catalog
This is a 0 zero risk PR, functional change just adds a project metadata file for foundation to consume.
> Experimenting with Software Catalog for Foundation - Add foundation.yaml

- app/features/sherlock/changesets/list/applied-changesets-panel.tsx
- app/features/sherlock/changesets/list/changeset-entry.tsx
- app/features/sherlock/chart-releases/chart-release-link-chip.tsx
- app/routes/_layout.review-changesets.tsx
This page means a lot more now that Sherlock links to it. Some UX improvements:
Before:
After:
Before:
After, upon page load:
After, if you expand the dropdown:
This does remove the refresh-only option from the UI. I don't think people should ever use that now, because it would run deploy hooks without having done the deployment. I think allowing just "run deployment" and "do nothing" as options is sufficient.
Ran it! See above 🎉 
Pretty low -- I'm not changing the mechanics of this page much, just what text is shown where. My final tests were running it against Sherlock prod, so that's as real as it gets.
> [DDO-3051] Improve "Review Version changes" UX

- app/features/sherlock/chart-releases/change-versions/change-chart-release-versions-panel.tsx
- app/features/sherlock/chart-versions/set/chart-version-picker.tsx
- app/routes/_layout.charts.$chartName.chart-releases.$chartReleaseName.change-versions.tsx
- app/routes/_layout.clusters.$clusterName.($filterNamespace).chart-releases.$namespace.$chartName.change-versions.tsx
- app/routes/_layout.clusters.$clusterName.($filterNamespace).chart-releases.add.$chartName.tsx
- app/routes/_layout.environments.$environmentName.chart-releases.$chartName.change-versions.tsx
- app/routes/_layout.environments.$environmentName.chart-releases.add.$chartName.tsx
- package-lock.json
- package.json
Add Beehive support for https://github.com/broadinstitute/sherlock/pull/295:
This means that we now have an enabled/disabled toggle for setting a custom helmfile ref:
I manually tested the following use cases locally:
* Add chart release to environment and cluster (with and without custom helmfile ref)
* Change helmfileRef using "change versions" from environment, cluster, and chart pages
* Monolith promotion does not raise error, or copy helmfileRef settings from another environment
* Monolith promotion *does* change helmfileRef to latest chart release version tag when no custom helmfileRef is set, and Sherlock's `helmfileRefDefaultToChartReleaseTags` config flag is set to true
> [DDO-3142] Make helmfileRef overrides optional

- app/features/sherlock/users/edit/user-editable-fields.tsx
- app/features/sherlock/users/list/match-user.ts
- app/features/sherlock/users/set/sidebar-select-user.tsx
- app/features/sherlock/users/view/user-details.tsx
- app/helpers/csp.server.ts
- app/routes/_layout.users.$userEmail.edit.tsx
- app/routes/_layout.users.$userEmail.tsx
- app/routes/_layout.users.tsx
- package-lock.json
- package.json
- setup-env.bash
DM button relies on https://github.com/broadinstitute/terra-helmfile/pull/4603
And the edit page for your own user:
Shows slackID/slackUsername when available and uses nameFrom instead of the deprecated nameInferredFromGithub.
Local testing against real Sherlock (since local Sherlock mocks out the user stuff too much to make this interface work quite right).
Super low
> [DDO-3143] Display Slack info on profile

- app/routes/_layout.apps.$chartName._index.tsx
- app/routes/_layout.apps.$chartName.tsx
- app/routes/_layout.apps.tsx
Old rule was "if you're deployed in dev and have a git repo configured for your chart, you'll be on the app view page."
New rule is just "if you have a git repo configured for your chart, you'll be on the app view page."
There's handling for if the app isn't deployed in any environments, there's a link to the chart instance list page which is the closest proxy.
While maybe it'll be confusing for things like Beehive and Sherlock and D2P to be in the list... I actually think them being in the list is better than not, because now we can say "if you want to go to prod to go broad.io/beehive/apps" and people will always get guided to the right place.
Tested locally, risk very low
> [DDO-3180] Show datarepo and other apps in the app view

- app/features/sherlock/environments/view/environment-details.tsx
Expands out all the filter parameters so Argo won't try to read them out of the user's last settings.
Local -- tiny change, see diff
Very low
> [DDO-3169] Reset labels and other filters in Argo list link

- app/features/sherlock/chart-releases/view/app-instance-entry-info.tsx
Before:
After: (ignore the broken images, ArgoCD badges don't work locally)
> [DDO-3252] Fix app view page alignment

- app/features/sherlock/environments/new/environment-creatable-fields.tsx
Improves the help text for the user when creating an environment. Also the error message returned when pattern validation fails now includes information about what the regex pattern being checked against for the environment name is expecting.
I have tested this by running a local instance of beehive, and then verifying the new help and error text displays as expected.
This doesn't actually change any application behavior, just provides more detailed messaging to the user.
Here's what the new user message and error text look like
I'm using the title field to show the error message on failing to match the pattern based on reccomendation in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) for `HTMLInputElement`
> DDO-3391 Improve Ux Messaging and Error Message for environment name validation

- app/features/sherlock/changesets/list/changeset-entry.tsx
Turns out this is fallout from https://github.com/broadinstitute/sherlock/pull/478 -- the detection of when a changelog was complete was mis-ordered.
This doesn't cross my threshold of being a big deal -- the changelog is still shown, just with a warning that other changes might be included.
Fixes the issue locally
Very low
> [DDO-3470] Fix changeset explanations

- .editorconfig
- .github/CODEOWNERS
- CONTRIBUTING.md
- DESIGN.md
- README.md
- scripts/build
- scripts/run
- scripts/setup
An MVP implementation of the [GitHub Repo Standards](https://broadworkbench.atlassian.net/wiki/spaces/TLR/pages/2952298505/GitHub+Repo+Standards#build) doc, taking a more minimal approach than some other repos due to the small scale and contributor list of this project.
- Modifies README.md
- Adds CONTRIBUTING.md
- Adds DESIGN.md
- Adds .editorconfig
- Adds .github/CODEOWNERS
- Adds ./scripts/run
- Adds ./scripts/build
- Moves and modifies setup-env.bash to ./scripts/setup
> [DDO-3557] Repo Standards Implementation MVP

- app/features/sherlock/changesets/recreate/changeset-recreate-button.tsx
- app/features/sherlock/chart-releases/chart-release-link-chip.tsx
- app/features/sherlock/chart-releases/view/chart-release-details.tsx
- app/features/sherlock/environments/view/environment-details.tsx
- app/routes/api.argocd.badge.ts
Like https://github.com/broadinstitute/sherlock/pull/527, replaces hostname and namespace references.
This doesn't mean that the ArgoCD badges will necessarily work -- they may fail, but rather than spending several days figuring out how to make those keep working I'm just going to tell people that they might fail. 🤷
> [DDO-3527] Cut over ArgoCD

- app/features/sherlock/deploy-hooks/new/new-deploy-hook-action.server.ts
The parse is done for edits but not for new ones. This does imply that no one has tried to create a new slack deploy hook since the advent of Beehive's new notifications... but I'm just going to take that as "I made good selections myself originally and no one's felt the need to add notifs for additional channels"
Manual, replicated Olivia's issue and fixed it. This is sorta the roughest edge of Remix, it is what it is
Very low, can't be more broken than it is now
> [DDO-3609] Parse mentionPeople to bool

- app/features/sherlock/role-assignments/delete/role-assignment-delete-description.tsx
- app/features/sherlock/role-assignments/edit/role-assignment-editable-fields.tsx
- app/features/sherlock/role-assignments/list/list-role-assignment-user-button-text.tsx
- app/features/sherlock/role-assignments/list/match-role-assignment-by-user.ts
- app/features/sherlock/role-assignments/list/role-assignment-sorter.ts
- app/features/sherlock/role-assignments/new/role-assignment-creatable-fields.tsx
- app/features/sherlock/role-assignments/view/role-assignment-details.tsx
- app/features/sherlock/roles/list/self-user-can-break-glass-into-role.ts
- app/features/sherlock/roles/view/role-details.tsx
- app/routes/_layout._index.tsx
- app/routes/_layout.roles.$roleName.assignments.$userEmail.delete.tsx
- app/routes/_layout.roles.$roleName.assignments.$userEmail.edit.tsx
- app/routes/_layout.roles.$roleName.assignments.$userEmail.tsx
- app/routes/_layout.roles.$roleName.assignments.new.tsx
- app/routes/_layout.roles.$roleName.assignments.tsx
- app/routes/_layout.roles.$roleName.tsx
- app/routes/_layout.roles.tsx
- package-lock.json
- package.json
First pass at a role assignments UI for Beehive. This PR also adds a link to the Roles view from the front page.
There are two flavors of experience. Sherlock Super Admins can universally create/edit/delete roles and assignments ([video](https://github.com/broadinstitute/beehive/assets/60902147/a69270fc-dd0f-45d9-bce2-c24931d897fa)). Regular users can create/edit/delete role assignments, but only for themselves, in roles that they can break-glass into ([video](https://github.com/broadinstitute/beehive/assets/60902147/000be1b3-6919-4c36-83b3-cc4c862469dc
)).
Note that this distinction is purely for improved UX, permission controls are implemented server-side.
> [DDO-3670] Breakglass role assignments UI

- .github/workflows/dependabot-approve.yaml
- CONTRIBUTING.md
Documents two-reviewer rule; adds GHA that lends an approval to dependabot PRs to make that smoother
> [DDO-3748] Document two-reviewer

- app/root.tsx
...by setting an `X-Beehive-Ignore-Github` header. This is helpful for automatic scanning of Beehive. Sarah G knows that bypassing this will break parts of Beehive, that's okay by her.
Tested locally. The misc page does indeed break a little bit as expected, I'm sure others would too. No one will accidentally trigger this so I think it's fine.
Low
> [DDO-3754] Allow programmatically bypassing GitHub login

- app/routes/_layout._index.tsx
Copilot autocompleted the joke about them being chocolate chip after I wrote "The cookies are all mandatory,"
~~Believe it or not I think this helps satisfy the cookie warning entry on the prod readiness checklist. I'm awaiting approval from Sarah T that this isn't a foot-gun.~~ This part technically isn't required but I already prepped the PR so idk I wanna post the joke.
> [DDO-3757] Cookie Warning

- app/helpers/csp.server.ts
Per Sarah G this is deprecated and it's now showing up as a low finding in Zap. Browsers that support it will fall back to default-src [(which we set to the same thing)](https://github.com/broadinstitute/beehive/blob/main/app/helpers/csp.server.ts#L19) so this is very safe to do.
"it loads" (CSP is the same everywhere so 🤷)
Astoundingly low
> [DDO-3777] Remove prefetch-src from CSP

- app/features/sherlock/clusters/cluster-edit-help-copy.tsx
- app/features/sherlock/clusters/edit/cluster-editable-fields.tsx
- app/features/sherlock/environments/edit/edit-environment-sidebar-modes.ts
- app/features/sherlock/environments/edit/environment-editable-fields.tsx
- app/features/sherlock/roles/set/sidebar-select-role.tsx
- app/routes/_layout.clusters.$clusterName.edit.tsx
- app/routes/_layout.clusters.new.tsx
- app/routes/_layout.environments.$environmentName.edit.tsx
- app/routes/_layout.environments.new.tsx
Borrows Chelsea's Role select sidebar components. Easy for Environment since that edit panel already had sidebar capability; added sidebar capability to Cluster.
A subsequent PR will remove the suitability toggle before Sherlock removes that capability.
Manually against dev. The only issue is actually a Sherlock-side issue with a fix proposed in https://github.com/broadinstitute/sherlock/pull/603.
Low
> [DDO-3776] Environment/Cluster Required Role UI

- app/features/sherlock/environments/edit/environment-editable-fields.tsx
- app/routes/_layout.environments.$environmentName.edit.tsx
- app/routes/_layout.environments.new.tsx
- package-lock.json
- package.json
> [DDO-3789] Expose Janitor toggle

- app/routes/_layout.environments.$environmentName.deploy-hooks.github-actions.$id.test-run.tsx
- app/routes/_layout.environments.$environmentName.deploy-hooks.slack.$id.test-run.tsx
As part of #511 I realized that I forgot to add UI pages for testing environment-level deploy hooks. I guess no one's noticed because folks don't really make those much, it's just been me for Slacks. Whatever, not that much code to add the pages and the API already exists.
Manual against prod, I used dry-run which still exercises the POST
Low
> [DDO-3787] Fix two more broken links

- app/features/sherlock/clusters/edit/cluster-editable-fields.tsx
- app/features/sherlock/environments/edit/environment-editable-fields.tsx
- app/routes/_layout.clusters.$clusterName.edit.tsx
- app/routes/_layout.clusters.new.tsx
- app/routes/_layout.environments.$environmentName.edit.tsx
- app/routes/_layout.environments.new.tsx
...for environments and clusters, not for roles where it's still a thing.
Requires https://github.com/broadinstitute/thelma/pull/309 first to be safe. Technically the field is unused already.
Locally
Low
> [DDO-3785] Remove references to suitability

- app/routes/_layout.environments.$environmentName.change-versions.tsx
I'm choosing not to add filterToMatchingBranches to the UI because I think that'll just be more confusing to people, but while scoping it I did notice a typo.
> [DDO-3831] Fix typo

- package-lock.json
- package.json
https://github.com/broadinstitute/beehive/security/dependabot/50 has a better description of what's going on here than I could write. This fixes it.
Booted it up locally. Cookie didn't fall over. Close enough.
Low. I looked at the changelog myself.
> [DDO-3908] Force-update cookie dependency

- app/features/sherlock/environments/edit/environment-editable-fields.tsx
- package-lock.json
- package.json
As outlined in [DDO-3902](https://broadworkbench.atlassian.net/browse/DDO-3902), adds a Beehive environment edit field for the Terra service banner bucket. Setting the bucket will allow for future versions of Sherlock to update the Terra UI GCS banner file which corresponds to the Terra UI banner. For now, all this does is update the database, so my plan is to merge this PR but have it deployed to prod Beehive only after the Sherlock feature goes out.
Creating a template
Creating a BEE
Updating a template or BEE or viewing the "Edit Metadata" panel
[DDO-3902]: https://broadworkbench.atlassian.net/browse/DDO-3902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
I set beehive-dev to this branch and tested the feature, verifying the changes in …
> [DDO-3902] Add service banner bucket edit field for environments

- package-lock.json
- package.json
Specifically uses Tailwind v3 instead of v4, which introduces a lot of changes and breaks the build. More info [here](https://stackoverflow.com/questions/79383705/cannot-build-frontend-using-vite-tailwindcss-with-postcss). TL;DR: Tailwind v4 is now the latest version and since we don't specify v3, we're getting v4 which is incompatible with this codebase.
I ran this branch locally and ensured that local Beehive + Sherlock work.
> [DDO-3655] Use Tailwind v3

- app/features/sherlock/service-alerts/new/service-alert-creatable-fields.tsx
Origin: DDO-4280
Fix for service alerts creation UI menu; text boxes are un-changable currently. 
This fixes the value var within the TextField definitions. 
Additionally fixing usage of default values.
> Js DDO-4280
